### ISSUE TITLE
boot first

### ISSUE THREAD

**Issue by NamWoo** [NamWoo/My_ML_Agents#10]
![photo_2021-12-15_20-45-46](https://user-images.githubusercontent.com/8021479/146180912-2cc11a92-ab58-4560-b33a-e08f8a29dceb.jpg)

![aa57e835-a658-4453-bbaf-1e6904c5f67c](https://user-images.githubusercontent.com/8021479/146155674-b243b60e-18a8-483a-98e7-e1369e56b4f7.jpeg)

![b4c937b8-fd87-43f6-9890-e7a14722d1e4](https://user-images.githubusercontent.com/8021479/146155593-32fb4ca5-1d39-4f51-a585-4b21a1e167f5.png)

**Comment by NamWoo** [comment]
참고 사진
![Screenshot from 2021-12-15 22-52-25](https://user-images.githubusercontent.com/8021479/146199238-d5295019-20fa-4b99-8ed8-ed0aad6e87f4.png)
들
![Screenshot from 2021-12-15 22-54-35](https://user-images.githubusercontent.com/8021479/146199241-af22baaf-6e24-41d9-a42d-578d4e6f314b.png)

**Comment by NamWoo** [comment]
![Screenshot from 2021-12-15 22-57-20](https://user-images.githubusercontent.com/8021479/146199723-739b01c5-9aa0-4320-bbb5-d418e0100f35.png)
![Screenshot from 2021-12-15 22-57-46](https://user-images.githubusercontent.com/8021479/146199726-7a1cb40f-b614-4a78-a90f-18c36769c17e.png)

**Comment by NamWoo** [comment]
![Screenshot from 2021-12-15 23-21-45](https://user-images.githubusercontent.com/8021479/146203618-c8ae4df2-a166-431f-b1c4-3dcd3e2a9791.png)
![Screenshot from 2021-12-15 23-34-04](https://user-images.githubusercontent.com/8021479/146205723-62ac2a57-cd0c-43e3-8941-550ec290fcfe.png)

**Comment by dnrwo1088** [comment]
![image](https://user-images.githubusercontent.com/44999855/146317061-eed35898-1b9e-4d85-9aa7-965d69d8bf42.png)

**Comment by NamWoo** [comment]
![image](https://user-images.githubusercontent.com/8021479/146326486-ec6bcf5e-75f8-4334-ba7a-273995f4a533.png)


![photo_2021-12-16_16-22-00](https://user-images.githubusercontent.com/8021479/146326085-871c722f-b30a-4a39-b691-12c50c593892.jpg)
![photo_2021-12-16_16-22-07](https://user-images.githubusercontent.com/8021479/146326090-59d51129-d27f-4a34-afd9-f61a1f722d47.jpg)
![photo_2021-12-16_16-22-08](https://user-images.githubusercontent.com/8021479/146326093-387917c7-995d-461e-b9ac-b08be9ac25af.jpg)
![photo_2021-12-16_16-22-09](https://user-images.githubusercontent.com/8021479/146326094-33a0d4ac-4b34-4fcf-867f-1b0033bafc13.jpg)
![photo_2021-12-16_16-22-10](https://user-images.githubusercontent.com/8021479/146326096-4778cdac-1564-4e14-8a0b-0ce43c9e703d.jpg)
![photo_2021-12-16_16-22-11](https://user-images.githubusercontent.com/8021479/146326097-086edb34-7682-442f-b8ba-0f7aa889ee1c.jpg)
![photo_2021-12-16_16-22-12](https://user-images.githubusercontent.com/8021479/146326101-c1d719ba-2e75-4f97-9f74-cfb2aaf0cae2.jpg)
![photo_2021-12-16_16-22-13](https://user-images.githubusercontent.com/8021479/146326103-cd39622b-7320-4453-9ada-ae74a61f4562.jpg)
![photo_2021-12-16_16-22-13 (2)](https://user-images.githubusercontent.com/8021479/146326104-8588c163-df47-48e5-acbd-803dc628949b.jpg)
![photo_2021-12-16_16-22-14](https://user-images.githubusercontent.com/8021479/146326106-5f07f5b5-d260-464b-9182-99681bf6f928.jpg)
![photo_2021-12-16_16-22-15](https://user-images.githubusercontent.com/8021479/146326109-c1a56c85-679b-4019-b087-d8af13984547.jpg)

---
![photo_2021-12-16_16-36-45](https://user-images.githubusercontent.com/8021479/146328406-70bc098d-e5f6-438d-b8f0-18a7045ed495.jpg)
![photo_2021-12-16_16-36-46](https://user-images.githubusercontent.com/8021479/146328412-8c25e510-e952-4942-960a-aca48ef683b6.jpg)
![photo_2021-12-16_16-36-48](https://user-images.githubusercontent.com/8021479/146328413-86adcbdd-2465-46ca-b033-545e4f385ed5.jpg)
![photo_2021-12-16_16-36-49](https://user-images.githubusercontent.com/8021479/146328414-7eb95bb2-6073-4e55-b1ea-50750558a458.jpg)
![photo_2021-12-16_16-36-50](https://user-images.githubusercontent.com/8021479/146328416-9a77e513-9b82-4413-ac7a-95dc8f341c8a.jpg)
![photo_2021-12-16_16-36-51](https://user-images.githubusercontent.com/8021479/146328417-59b4f971-8ee3-4670-9864-b3b2d5d7cbf6.jpg)
![photo_2021-12-16_16-36-52](https://user-images.githubusercontent.com/8021479/146328420-44912d8b-2f63-4c8a-86cd-619fa9994aa8.jpg)
![photo_2021-12-16_16-36-53](https://user-images.githubusercontent.com/8021479/146328423-4da8633f-b40a-43f8-ab40-11030f67849d.jpg)
![photo_2021-12-16_16-36-54](https://user-images.githubusercontent.com/8021479/146328426-6a088a76-1a82-4c7c-96ea-e071b1f5b77f.jpg)
![photo_2021-12-16_16-36-54 (2)](https://user-images.githubusercontent.com/8021479/146328427-9b20f734-c9d5-431d-a8ed-3fc793549adc.jpg)

**Comment by NamWoo** [comment]
![photo_2021-12-16_16-22-00](https://user-images.githubusercontent.com/8021479/146326085-871c722f-b30a-4a39-b691-12c50c593892.jpg)
![photo_2021-12-16_16-22-07](https://user-images.githubusercontent.com/8021479/146326090-59d51129-d27f-4a34-afd9-f61a1f722d47.jpg)
![photo_2021-12-16_16-22-08](https://user-images.githubusercontent.com/8021479/146326093-387917c7-995d-461e-b9ac-b08be9ac25af.jpg)
![photo_2021-12-16_16-22-09](https://user-images.githubusercontent.com/8021479/146326094-33a0d4ac-4b34-4fcf-867f-1b0033bafc13.jpg)
![photo_2021-12-16_16-22-10](https://user-images.githubusercontent.com/8021479/146326096-4778cdac-1564-4e14-8a0b-0ce43c9e703d.jpg)
![photo_2021-12-16_16-22-11](https://user-images.githubusercontent.com/8021479/146326097-086edb34-7682-442f-b8ba-0f7aa889ee1c.jpg)
![photo_2021-12-16_16-22-12](https://user-images.githubusercontent.com/8021479/146326101-c1d719ba-2e75-4f97-9f74-cfb2aaf0cae2.jpg)
![photo_2021-12-16_16-22-13](https://user-images.githubusercontent.com/8021479/146326103-cd39622b-7320-4453-9ada-ae74a61f4562.jpg)
![photo_2021-12-16_16-22-13 (2)](https://user-images.githubusercontent.com/8021479/146326104-8588c163-df47-48e5-acbd-803dc628949b.jpg)
![photo_2021-12-16_16-22-14](https://user-images.githubusercontent.com/8021479/146326106-5f07f5b5-d260-464b-9182-99681bf6f928.jpg)
![photo_2021-12-16_16-22-15](https://user-images.githubusercontent.com/8021479/146326109-c1a56c85-679b-4019-b087-d8af13984547.jpg)

**Comment by NamWoo** [comment]
![photo_2021-12-16_16-53-56](https://user-images.githubusercontent.com/8021479/146330606-03d8e44d-dee4-462b-af8f-e170a07f127a.jpg)
![photo_2021-12-16_16-53-57](https://user-images.githubusercontent.com/8021479/146330611-2e445f0c-8327-4d0a-9476-2e4a5bef1338.jpg)
![photo_2021-12-16_16-54-01](https://user-images.githubusercontent.com/8021479/146330614-3514a0da-a6fd-4e0f-904c-333142a12259.jpg)
